---
title: Process anonymised data
author: "Miguel Rodo"
format:
  html:
    embed-resources: true
--- 

# Introduction

```{r}
# Initial set-up ----------------------------------------------------------

# saving results? clear wd first
currObjVec = ls()

# find library containing raw data
dataprepPath = projr::projr_dir_get(
  "project", "scripts", "R"
)
dirFunc = function(x) paste0(dataprepPath, "/", x)
devtools::load_all()
source(file = "scripts/R/libraries.R")

# Individual datasets -----------------------------------------------------

# h564Tbl
source(file = dirFunc("H56-CD4.R"))

# h568Tbl
source(file = dirFunc("H56-CD8.R"))

# l4Tbl
source(file = dirFunc("BCG-CD4.R"))

# l8Tbl
source(file = dirFunc("BCG-CD8.R"))

# lOrigMainTbl
source(file = dirFunc("Main.R"))

# idri
source(file = dirFunc("ID93.R"))

# h1
source(file = dirFunc("H1.R"))

# megapool
source(file = dirFunc("Megapool.R"))

# aeras402
source(file = dirFunc("AERAS402.R"))

# Joining and calculating -------------------------------------------------

# join
source(file = dirFunc("Data_Join.R"))

# il17
source(file = dirFunc("IL_17-Calc_And_Removal.R"))

# sub time zero
source(file = dirFunc("Sub_Baseline.R"))

# summary statistics
source(file = dirFunc("Summ_Stat_Calc.R"))

# Saving ------------------------------------------------------------------

#' making availabe in package
projr::projr_use_data(bl17ExcTbl, overwrite = TRUE) 
projr::projr_use_data(bl17ExcITbl, overwrite = TRUE)
projr::projr_use_data(join17ExcTbl, overwrite = TRUE)
projr::projr_use_data(join17ExcITbl, overwrite = TRUE)
projr::projr_use_data(join17IncITbl, overwrite = TRUE)
projr::projr_use_data(megITbl, overwrite = TRUE)
projr::projr_use_data(sub17ExcTbl, overwrite = TRUE)
projr::projr_use_data(sub17ExcITbl, overwrite = TRUE)
projr::projr_use_data(tmax17ExcTbl, overwrite = TRUE)
projr::projr_use_data(tmax17ExcITbl, overwrite = TRUE)
projr::projr_use_data(tmaxSub17ExcTbl, overwrite = TRUE)
projr::projr_use_data(tmaxSub17ExcITbl, overwrite = TRUE)
projr::projr_use_data(blSingle17Tbl, overwrite = TRUE)
projr::projr_use_data(single17Tbl, overwrite = TRUE)
projr::projr_use_data(single17ITbl, overwrite = TRUE)
projr::projr_use_data(tmaxSingle17Tbl, overwrite = TRUE)
projr::projr_use_data(tmaxSingle17ITbl, overwrite = TRUE)
projr::projr_use_data(subSingle17Tbl, overwrite = TRUE)
projr::projr_use_data(subSingle17ITbl, overwrite = TRUE)
projr::projr_use_data(tmaxSubSingle17Tbl, overwrite = TRUE)
projr::projr_use_data(tmaxSubSingle17ITbl, overwrite = TRUE)

# write to spreadsheet

path_save_vacc <- projr::projr_path_get(
    "output", "DataTidy19RodoVaccComp.csv"
  )
if (file.exists(path_save_vacc)) {
  file.remove(path_save_vacc)
}
write.csv(
  join17IncITbl %>%
    spread(key = cytCombo, value = resp) %>%
    select(-prid),
  path_save_vacc
)
path_save_meg <- projr::projr_path_get(
    "output", "DataTidy19RodoVaccComp.csv"
  )
if (file.exists(path_save_meg)) {
  file.remove(path_save_meg)
}
write.csv(
  joinMegITbl1 %>%
    spread(key = cytCombo, value = resp) %>%
    select(-c(prid, timePoint, vaccine, stim, infxn)),
  path_save_vacc
)
```

Check that the processed data matches old processed data:

```{r}
load(
  projr::projr_path_get(
    "data-raw-public", "check", "join17IncITbl.rda"
    )
)
old_data <- join17IncITbl
load(
  projr::projr_path_get(
    "cache", "projr", paste0("v", projr::projr_version_get()), "data", "join17IncITbl.rda"
  )
)
new_data <- join17IncITbl
stopifnot(identical(new_data, old_data))
```