library(plyr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
library(stringr, warn.conflicts = FALSE)
library(magrittr, warn.conflicts = FALSE)
library(openxlsx, warn.conflicts = FALSE)
library(tibble, warn.conflicts = FALSE)
library(pryr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)